env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:functional/recommended

plugins:
  - react
  - functional

rules:
  functional/functional-parameters: 0
  functional/immutable-data: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/no-throw-statement: 0
  functional/no-try-statement: 0
  no-console: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/prop-types: 0
  react/react-in-jsx-scope: 0
